### ISSUE TITLE
Error running pgtune

### ISSUE THREAD

**Issue by roshanjonah** [satya10x/pgtune#1]
Hi there, 

Followed all the install steps and change DB details...when running it, I am getting the following error...

```
~/pgtune# pgtune
Traceback (most recent call last):
  File "/usr/local/bin/pgtune", line 11, in <module>
    load_entry_point('pgtune', 'console_scripts', 'pgtune')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/pgtune/pgtune/tuner.py", line 5, in <module>
    from pglast import Node, parse_sql
ModuleNotFoundError: No module named 'pglast'
```

Your help would be much appreciated :)

**Comment by roshanjonah** [comment]
I installed that module manually and now I am getting the following...

```
~/pgtune# pgtune
column "total_time" does not exist
LINE 1: SELECT query FROM PG_STAT_STATEMENTS order by total_time/cal...
                                                      ^

```

I then went on to check if PG_STAT_STATEMENT existed and it does

```
You are now connected to database "xxx" as user "postgres".
xxx=# SELECT *
xxx-# FROM pg_available_extensions
xxx-# WHERE
xxx-#     name = 'pg_stat_statements' and
xxx-#     installed_version is not null;
        name        | default_version | installed_version |                                comment
--------------------+-----------------+-------------------+------------------------------------------------------------------------
 pg_stat_statements | 1.8             | 1.8               | track planning and execution statistics of all SQL statements executed
(1 row)
```

**Comment by satya10x** [comment]
Ah! I'm terribly sorry, I just saw these texts. Not sure why github didn't notify me for it, or maybe it did and it got lost in the noise. I will go through this, and figure out a solution.

**Comment by pgyogesh** [comment]
@satya10x I have created pull request to fix this
